
-- Create demo user accounts in Supabase Auth
-- Note: These will be created through the auth.users table via Supabase's auth system
-- We need to insert them manually as test accounts

-- Insert demo admin account
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  confirmation_sent_at,
  confirmation_token,
  recovery_sent_at,
  recovery_token,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_token_current,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES
(
  '00000000-0000-0000-0000-000000000000',
  gen_random_uuid(),
  'authenticated',
  'authenticated',
  'admin@digital4pulse.edu',
  crypt('password123', gen_salt('bf')),
  now(),
  now(),
  '',
  null,
  '',
  '',
  '',
  null,
  null,
  '{"provider":"email","providers":["email"]}',
  '{"first_name":"Demo","last_name":"Admin"}',
  false,
  now(),
  now(),
  null,
  null,
  '',
  '',
  null,
  '',
  0,
  null,
  '',
  null,
  false,
  null
),
(
  '00000000-0000-0000-0000-000000000000',
  gen_random_uuid(),
  'authenticated',
  'authenticated',
  'user@digital4pulse.edu',
  crypt('password123', gen_salt('bf')),
  now(),
  now(),
  '',
  null,
  '',
  '',
  '',
  null,
  null,
  '{"provider":"email","providers":["email"]}',
  '{"first_name":"Demo","last_name":"User"}',
  false,
  now(),
  now(),
  null,
  null,
  '',
  '',
  null,
  '',
  0,
  null,
  '',
  null,
  false,
  null
);
