// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dlyqplfyaxyylkjotnfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRseXFwbGZ5YXh5eWxram90bmZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwODc5ODYsImV4cCI6MjA2MDY2Mzk4Nn0.JGgyW3-wscIeECepW1grSgIu-YCaYdgUIgskCJwSmz8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);